### ISSUE TITLE
Алгоритмическое улучшение быстрого возведения в степень 

### ISSUE THREAD

**Issue by kofes** [mrnosomebody/c-#2]
https://github.com/mrnosomebody/c-/blob/3fdb40308df2c1a085e4eb3f616f6dcb11d9813f/main.cpp#L14-L22

Возможно алгоритмически ускорить работу цикла, за счет постоянного умножения `num` на саму себя на каждой итерации, и увеличении `result` в `num` раз при проверке значения степени на нечетность (также на каждой итерации).

**Comment by mrnosomebody** [comment]
выполняется за О(log n)
