### ISSUE TITLE
Статические методы

### ISSUE THREAD

**Issue by kofes** [mrnosomebody/c-#4]
https://github.com/mrnosomebody/c-/blob/3fdb40308df2c1a085e4eb3f616f6dcb11d9813f/main.cpp#L43

Если метод не использует не публичные поля/методы класса, то его следует вынести в отдельную функцию, или, если он (метод) подходит логически для данного класса, но также не использует  не публичные поля/методы класса, то метод следует сделать статичным.

**Comment by mrnosomebody** [comment]
![Uploading image.png…]()

**Comment by mrnosomebody** [comment]
нод и нок сделал статик
