### ISSUE TITLE
Дублирующийся код

### ISSUE THREAD

**Issue by kofes** [mrnosomebody/c-#9]
https://github.com/mrnosomebody/c-/blob/3fdb40308df2c1a085e4eb3f616f6dcb11d9813f/main.cpp#L12
https://github.com/mrnosomebody/c-/blob/3fdb40308df2c1a085e4eb3f616f6dcb11d9813f/main.cpp#L251

Шаблонная функция делает тоже самое. что делает отдельная "специализация" для рациональных чисел (убрать "специализацию").

Более того, присутствует реализация отдельного метода для комплексных чисел
https://github.com/mrnosomebody/c-/blob/3fdb40308df2c1a085e4eb3f616f6dcb11d9813f/main.cpp#L397
Она также излишня, т.к. реализованная шаблонная функция может и работать и с комплексными числами.

**Comment by mrnosomebody** [comment]
3 пункт - 
2 исправил 
1 оставил
